using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace SharpSheets.Generators {

	[Generator]
	public class ExpressionUsageGenerator : IIncrementalGenerator {

		private const string TargetInterfaceMetadataName = "SharpSheets.Evaluations.IExpression`1";

		public void Initialize(IncrementalGeneratorInitializationContext ctx) {

			IncrementalValueProvider<EquatableArray<string>> typeSyntaxProvider = ctx.SyntaxProvider.CreateSyntaxProvider(
				predicate: static (node, _) =>
					node is GenericNameSyntax || node is QualifiedNameSyntax ||
					node is IdentifierNameSyntax || node is NullableTypeSyntax,
				transform: static (ctx, ct) => {
					// get a TypeSyntax to ask semantic model about
					TypeSyntax? ts = ctx.Node switch {
						GenericNameSyntax g => g,
						QualifiedNameSyntax q => q,
						IdentifierNameSyntax i => i,
						NullableTypeSyntax n => n.ElementType,
						_ => null
					};

					if (ts is null) return new EquatableArray<string>();

					SemanticModel model = ctx.SemanticModel;
					ITypeSymbol? typeInfo =  model.GetTypeInfo(ts, ct).Type;

					if (typeInfo is null || typeInfo.Kind == SymbolKind.ErrorType) return new EquatableArray<string>();

					return new EquatableArray<string>(GetTypeComponents(typeInfo).ToArray());
				})
				.SelectMany(static (ts, _) => ts)
				.Collect()
				.Select(static (ts, _) => new EquatableArray<string>(ts.Distinct().OrderBy(s => s).ToArray()));

			ctx.RegisterSourceOutput(typeSyntaxProvider.Combine(ctx.CompilationProvider),
				static (spc, source) => ExecuteExpressionUsage(source.Left, source.Right, spc));
		}

		private static IEnumerable<string> GetTypeComponents(ITypeSymbol symbol) {
			if (!symbol.IsValueType && symbol.NullableAnnotation == NullableAnnotation.Annotated) {
				foreach (string componentType in GetTypeComponents(symbol.WithNullableAnnotation(NullableAnnotation.NotAnnotated))) {
					yield return componentType;
				}
			}
			else if (symbol is INamedTypeSymbol named && named.OriginalDefinition != null && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T) {
				ITypeSymbol underlying = named.TypeArguments[0];
				foreach (string componentType in GetTypeComponents(underlying)) {
					yield return componentType;
				}
			}
			else if (symbol.IsTupleType && symbol is INamedTypeSymbol tupleSymbol) {
				foreach (IFieldSymbol tupleField in tupleSymbol.TupleElements) {
					foreach (string componentType in GetTypeComponents(tupleField.Type)) {
						yield return componentType;
					}
				}
			}
			else if (symbol is IArrayTypeSymbol arraySymbol) {
				foreach (string componentType in GetTypeComponents(arraySymbol.ElementType)) {
					yield return componentType;
				}
			}
			else {
				yield return TypeData.Create(symbol).Minimal;

				if (symbol is INamedTypeSymbol namedSymbol && namedSymbol.TypeArguments.Length > 0) {
					foreach (ITypeSymbol typeArg in namedSymbol.TypeArguments) {
						foreach (string componentType in GetTypeComponents(typeArg)) {
							yield return componentType;
						}
					}
				}
			}
		}

		private static void ExecuteExpressionUsage(EquatableArray<string> foundTypes, Compilation compilation, SourceProductionContext context) {
			// generate the source code and add it to the output
			string? result = GenerateExpressionUsageCode(foundTypes, compilation, context.CancellationToken);
			// Create a separate partial class file
			if (!string.IsNullOrEmpty(result)) {
				context.AddSource($"Utilities.ExpressionUsage.g.cs", SourceText.From(result!, Encoding.UTF8));
			}
		}

		private static string? GenerateExpressionUsageCode(EquatableArray<string> foundTypes, Compilation compilation, CancellationToken ct) {
			ct.ThrowIfCancellationRequested();

			INamedTypeSymbol? targetInterfaceType = compilation.GetTypeByMetadataName(TargetInterfaceMetadataName);
			if (targetInterfaceType is null) {
				return null; // interface not found - nothing to do
			}

			StringBuilder sb = new StringBuilder();

			string dictionaryVariableName = "__generated__expression_type_lookup";

			sb.Append($@"// <auto-generated/>
#nullable enable
#pragma warning disable

using System.Diagnostics.CodeAnalysis;

namespace SharpSheets.Utilities {{

	{GeneratorMarkers.GeneratedCodeAttr}
	{GeneratorMarkers.CompilerGeneratedAttr}
	public static class ExpressionUsageMap {{

		private static readonly System.Collections.Generic.Dictionary<Type, Type> {dictionaryVariableName} = new System.Collections.Generic.Dictionary<Type, Type>() {{");

			foreach (string typeName in foundTypes) {
				if (compilation.ResolveTypeKey(typeName) is not INamedTypeSymbol type) { continue; }

				if (TryGetInterfaceTypeArgument(type, targetInterfaceType, out ITypeSymbol interfaceArg)) {
					sb.Append($@"
				{{ typeof({typeName}), typeof({TypeNameUtils.ReduceParameterTypeName(interfaceArg.ToFullDisplayString())}) }},");
				}
			}

			sb.Append($@"
			}};

		public static bool TryGetExpressionType(Type type, [MaybeNullWhen(false)] out Type expressionType) {{
			return {dictionaryVariableName}.TryGetValue(type, out expressionType);
		}}

	}}

}}

#pragma warning restore");

			return sb.ToString();
		}

		private static bool TryGetInterfaceTypeArgument(INamedTypeSymbol subject, INamedTypeSymbol targetInterfaceType, out ITypeSymbol interfaceArg) {
			if (subject.OriginalDefinition != null && SymbolEqualityComparer.Default.Equals(subject.OriginalDefinition, targetInterfaceType)) {
				foreach (ITypeSymbol typeArg in subject.TypeArguments) {
					if (typeArg.TypeKind != TypeKind.Error) {
						interfaceArg = typeArg;
						return true;
					}
				}
			}
			
			foreach (INamedTypeSymbol interfaceType in subject.AllInterfaces) {
				if (interfaceType.OriginalDefinition != null && SymbolEqualityComparer.Default.Equals(interfaceType.OriginalDefinition, targetInterfaceType)) {
					foreach (ITypeSymbol typeArg in interfaceType.TypeArguments) {
						if (typeArg.TypeKind != TypeKind.Error) {
							interfaceArg = typeArg;
							return true;
						}
					}
				}
			}

			interfaceArg = null!;
			return false;
		}

	}

}